<a href="https://colab.research.google.com/github/JamdhadeVikrant/Code/blob/main/DSBDA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import statistics as st

In [6]:
df=pd.read_csv("/content/sample_data/mnist_test.csv")

In [7]:
print(df.shape)
print(df.info())

(9999, 785)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB
None

In [28]:
df.head()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
df.mean()

7        4.443144
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...
0.663    0.000000
0.664    0.000000
0.665    0.000000
0.666    0.000000
0.667    0.000000
Length: 785, dtype: float64

In [19]:
print(df.loc[:,'7'].mean())

4.443144314431443

In [9]:
df.mean(axis=1)[0:5]

0    36.754140
1    12.575796
2    47.151592
3    24.510828
4    17.650955
dtype: float64

In [10]:
df.median()

7        4.0
0        0.0
0.1      0.0
0.2      0.0
0.3      0.0
        ...
0.663    0.0
0.664    0.0
0.665    0.0
0.666    0.0
0.667    0.0
Length: 785, dtype: float64

In [20]:
print(df.loc[:,'7'].median())

4.0

In [11]:
df.median(axis=1)[0:5]

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
dtype: float64

In [12]:
df.mode()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
print(df.loc[:,'7'].mode())

0    1
Name: 7, dtype: int64

In [13]:
df.mode(axis=1)[0:5]

   0
0  0
1  0
2  0
3  0
4  0

In [14]:
df.std()

7        2.895897
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...
0.663    0.000000
0.664    0.000000
0.665    0.000000
0.666    0.000000
0.667    0.000000
Length: 785, dtype: float64

In [22]:
print(df.loc[:,'7'].std())

2.8958970973214826

In [23]:
df.var()

7        8.38622
0        0.00000
0.1      0.00000
0.2      0.00000
0.3      0.00000
          ...
0.663    0.00000
0.664    0.00000
0.665    0.00000
0.666    0.00000
0.667    0.00000
Length: 785, dtype: float64

In [24]:
from scipy.stats import iqr
iqr(df['7'])

np.float64(5.0)

In [25]:
print(df.skew())

7        0.040279
0        0.000000
0.1      0.000000
0.2      0.000000
0.3      0.000000
           ...
0.663    0.000000
0.664    0.000000
0.665    0.000000
0.666    0.000000
0.667    0.000000
Length: 785, dtype: float64

In [26]:
df.describe

<bound method NDFrame.describe of       7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
0         0      0      0      0      0      0      0
1         0      0      0      0      0      0      0
2         0      0      0      0      0      0      0
3         0      0      0      0      0      0      0
4         0      0      0      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
9994      0      0      0      0      0      0      0
9995      0      0      0      0      0      0      0
9996      0      0      0      0      0      0      0
9997      0      0      0      0      0      0      0
9998      0      0      0      0      0      0      0

[9999 rows x 785 columns]>

In [27]:
df.describe(include='all')

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
count,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,...,9999.000000,9999.000000,9999.000000,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0
mean,4.443144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.179318,0.163616,0.052605,0.000600,0.0,0.0,0.0,0.0,0.0,0.0
std,2.895897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.674433,5.736359,2.420125,0.060003,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,253.000000,156.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0